name: accurate_ri_env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - blas=1.0
  - boost=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cmake=3.22.3
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.13
  - decorator=5.2.1
  - eigen=3.4.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fontconfig=2.14.2
  - fonttools=4.55.3
  - freetype=2.12.1
  - gcc_impl_linux-64=14.2.0
  - gcc_linux-64=14.2.0
  - gdb=14.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.16.0
  - gxx_impl_linux-64=14.2.0
  - gxx_linux-64=14.2.0
  - icu=73.1
  - importlib-metadata=8.6.1
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.58.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsanitizer=14.2.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mpfr=4.2.1
  - mysql=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - ninja=1.12.1
  - ninja-base=1.12.1
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - ply=3.11
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-boost=1.82.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pytest=8.3.4
  - python=3.12.0
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - readline=8.2
  - rhash=1.4.3
  - seaborn=0.13.2
  - setuptools=75.8.0
  - sip=6.7.12
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
